---
title: "Kate Young's CV"
name: Kate
surname: Young
position: "Research Assistant Professor"
address: "Department of Biostatistics & Data Science, University of Kansas Medical Center"
date: "`r format(Sys.time(), '%B %Y')`"
headcolour: blue
docname: CV
output: 
  vitae::markdowncv:
    theme: kjhealy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(vitae)
library(dplyr)
```

## Education

```{r education}
edu<- tibble::tribble(
  ~ degree, ~ year, ~ school, ~ location, ~ details,
  "PhD in Biostatistics", 2023, 'University of Kanasas Medical Center', 'Kansas City, KS',
  c('Advisor: Leonidas Bantis, PhD')
)
edu %>%
  detailed_entries(what = degree, when = year, where = school, with = location, 
                          why = details)
```

## Professional Positions

```{r professional}
prof <- tibble::tribble(
  ~ title, ~ years, ~ employer, 
  "Statistician II", "2020-2023", 'University of Kanasas Medical Center, Kansas City, KS',
  "Associate Biostatistician", "2018-2020", "PRA Health Sciences, Kansas City, KS"
)
prof %>%
  brief_entries(what = title, when = years, with = employer)
```

## Publications

```{r peerreviewed}
bib <- file.path("MyCV.bib")
bibliography_entries(bib) 
```
